### ISSUE TITLE
Adding pause button

### ISSUE THREAD

**Issue by CYB3R-G0D** [retrowars/retrowars#26] opened 2021-07-10 16:54 UTC
### Game can't be paused in between
While playing the game user is not provided with any pause button.

**Comment by JM480** [comment] 2022-04-10 22:47
This is a duplicate of #11.

**Comment by pserwylo** [comment] 2022-04-11 10:45
Thanks for the comment @JM480 (and @CYB3R-G0D for the report). Will close this as a duplicate and start to get working on the pause/menu.

**Closed by pserwylo** 2022-04-11 10:45 UTC
